homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto:1883
serial:
  port: tcp://host.docker.internal:8282
  adapter: ember
frontend:
  port: 8081
advanced:
  log_level: info
  network_key:
    - 149
    - 174
    - 2
    - 189
    - 150
    - 208
    - 70
    - 139
    - 41
    - 149
    - 66
    - 62
    - 244
    - 209
    - 20
    - 174
devices:
  '0xcc36bbfffe7fc69f':
    friendly_name: Despacho
  '0xcc36bbfffe7d2ce9':
    friendly_name: Habitación Papis
  '0xcc36bbfffe7fc692':
    friendly_name: Salón
  '0xcc36bbfffe7fc617':
    friendly_name: Habitación Esq
  '0xcc36bbfffe7d4754':
    friendly_name: Habitación Cen
