"""
Configuracion de las 13 zonas candidatas del estudio (Fase 1).
Las URLs de busqueda se rellenan con patrones reales de cada portal.
"""
from models import FireRisk, Zone
# ---------------------------------------------------------------------------
# Las 13 zonas con mayor puntuacion del estudio peninsular
# Preferencias personales (P11, max 9): especificadas por el usuario
# ---------------------------------------------------------------------------
ZONES: dict[str, Zone] = {
    z.id: z for z in [
        Zone(
            id="zamora_meseta",
            name="Zamora meseta central (Arcenillas, Villaralbo, Morales del Vino)",
            distance_madrid_min=150,
            distance_beach_min=None,
            distance_natural_pools_min=30,
            distance_supermarket_min=10,
            distance_health_center_min=8,
            distance_hospital_min=12,
            fire_risk=FireRisk.NULO,
            zone_preference=5.0,
            price_min=59_000,
            price_max=259_000,
            fotocasa_search_urls=(),
            habitaclia_search_urls=(
                "https://www.habitaclia.com/casas-zamora.htm",
            ),
            pisos_search_urls=(
                "https://www.pisos.com/venta/casas-zamora/habitaciones-3/jardin/",
            ),
            idealista_alert_keywords=("zamora", "arcenillas", "villaralbo", "morales del vino"),
        ),
        Zone(
            id="castellon_costa_norte",
            name="Castellon costa norte (Vinaros, Benicarlo, Peniscola)",
            distance_madrid_min=225,
            distance_beach_min=5,
            distance_natural_pools_min=30,
            distance_supermarket_min=5,
            distance_health_center_min=5,
            distance_hospital_min=8,
            fire_risk=FireRisk.MUY_BAJO,
            zone_preference=6.0,
            price_min=250_000,
            price_max=450_000,
            fotocasa_search_urls=(),
            habitaclia_search_urls=(
                "https://www.habitaclia.com/casas-vinaros.htm",
                "https://www.habitaclia.com/casas-benicarlo.htm",
            ),
            pisos_search_urls=(
                "https://www.pisos.com/venta/casas-vinaros/habitaciones-3/jardin/",
                "https://www.pisos.com/venta/casas-benicarlo/habitaciones-3/jardin/",
            ),
            idealista_alert_keywords=("vinaros", "benicarlo", "peniscola"),
        ),
        Zone(
            id="salamanca_alrededores",
            name="Salamanca alrededores capital (Doninos, Aldearrubia, Villamayor)",
            distance_madrid_min=120,
            distance_beach_min=None,
            distance_natural_pools_min=45,
            distance_supermarket_min=8,
            distance_health_center_min=8,
            distance_hospital_min=12,
            fire_risk=FireRisk.NULO,
            zone_preference=5.0,
            price_min=183_000,
            price_max=299_000,
            fotocasa_search_urls=(),
            habitaclia_search_urls=(
                "https://www.habitaclia.com/casas-salamanca.htm",
            ),
            pisos_search_urls=(
                "https://www.pisos.com/venta/casas-salamanca/habitaciones-3/jardin/",
            ),
            idealista_alert_keywords=("doninos", "aldearrubia", "villamayor", "carbajosa"),
        ),
        Zone(
            id="la_rioja_valle",
            name="La Rioja valle bajo (Alberite, Navarrete, Fuenmayor)",
            distance_madrid_min=165,
            distance_beach_min=None,
            distance_natural_pools_min=20,
            distance_supermarket_min=8,
            distance_health_center_min=5,
            distance_hospital_min=8,
            fire_risk=FireRisk.NULO,
            zone_preference=7.0,
            price_min=208_000,
            price_max=300_000,
            fotocasa_search_urls=(),
            habitaclia_search_urls=(
                "https://www.habitaclia.com/casas-la-rioja.htm",
            ),
            pisos_search_urls=(
                "https://www.pisos.com/venta/casas-villamediana_de_iregua/habitaciones-3/jardin/",
                "https://www.pisos.com/venta/casas-alberite/habitaciones-3/jardin/",
            ),
            idealista_alert_keywords=("alberite", "navarrete", "fuenmayor", "villamediana"),
        ),
        Zone(
            id="valencia_costa_norte",
            name="Valencia costa norte (Sagunto, Canet d'En Berenguer, Pucol)",
            distance_madrid_min=210,
            distance_beach_min=5,
            distance_natural_pools_min=15,
            distance_supermarket_min=5,
            distance_health_center_min=5,
            distance_hospital_min=8,
            fire_risk=FireRisk.MUY_BAJO,
            zone_preference=6.0,
            price_min=250_000,
            price_max=400_000,
            fotocasa_search_urls=(),
            habitaclia_search_urls=(
                "https://www.habitaclia.com/casas-valencia.htm",
            ),
            pisos_search_urls=(
                "https://www.pisos.com/venta/casas-sagunto/habitaciones-3/jardin/",
            ),
            idealista_alert_keywords=("sagunto", "canet d'en berenguer", "pucol"),
        ),
        Zone(
            id="palencia_alrededores",
            name="Palencia alrededores (Venta de Banos, Grijota, Reinoso)",
            distance_madrid_min=140,
            distance_beach_min=None,
            distance_natural_pools_min=60,
            distance_supermarket_min=8,
            distance_health_center_min=8,
            distance_hospital_min=18,
            fire_risk=FireRisk.NULO,
            zone_preference=5.0,
            price_min=159_000,
            price_max=207_000,
            fotocasa_search_urls=(),
            habitaclia_search_urls=(
                "https://www.habitaclia.com/casas-palencia.htm",
            ),
            pisos_search_urls=(
                "https://www.pisos.com/venta/casas-palencia/habitaciones-3/jardin/",
            ),
            idealista_alert_keywords=("venta de banos", "grijota", "reinoso", "palencia"),
        ),
        Zone(
            id="navarra_ribera",
            name="Navarra Ribera (Tudela, Cadreita, Valtierra)",
            distance_madrid_min=180,
            distance_beach_min=None,
            distance_natural_pools_min=60,
            distance_supermarket_min=5,
            distance_health_center_min=8,
            distance_hospital_min=8,
            fire_risk=FireRisk.BAJO,
            zone_preference=6.0,
            price_min=100_000,
            price_max=200_000,
            fotocasa_search_urls=(),
            habitaclia_search_urls=(
                "https://www.habitaclia.com/casas-tudela.htm",
            ),
            pisos_search_urls=(
                "https://www.pisos.com/venta/casas-tudela/habitaciones-3/jardin/",
            ),
            idealista_alert_keywords=("tudela", "cadreita", "valtierra", "ribera navarra"),
        ),
        Zone(
            id="burgos_sur",
            name="Burgos sur (Aranda de Duero, Lerma, Ribera del Duero)",
            distance_madrid_min=140,
            distance_beach_min=None,
            distance_natural_pools_min=60,
            distance_supermarket_min=8,
            distance_health_center_min=8,
            distance_hospital_min=18,
            fire_risk=FireRisk.MUY_BAJO,
            zone_preference=6.0,
            price_min=120_000,
            price_max=220_000,
            fotocasa_search_urls=(),
            habitaclia_search_urls=(
                "https://www.habitaclia.com/casas-burgos.htm",
            ),
            pisos_search_urls=(
                "https://www.pisos.com/venta/casas-burgos/habitaciones-3/jardin/",
            ),
            idealista_alert_keywords=("aranda de duero", "lerma", "penaranda de duero"),
        ),
        Zone(
            id="valladolid_rural",
            name="Valladolid rural (municipios meseta, sin pinar)",
            distance_madrid_min=120,
            distance_beach_min=None,
            distance_natural_pools_min=60,
            distance_supermarket_min=12,
            distance_health_center_min=10,
            distance_hospital_min=22,
            fire_risk=FireRisk.NULO,
            zone_preference=4.0,
            price_min=180_000,
            price_max=250_000,
            fotocasa_search_urls=(),
            habitaclia_search_urls=(
                "https://www.habitaclia.com/casas-valladolid.htm",
            ),
            pisos_search_urls=(
                "https://www.pisos.com/venta/casas-valladolid/habitaciones-3/jardin/",
            ),
            idealista_alert_keywords=("villaturiel", "santa maria del condado", "mansilla"),
        ),
        Zone(
            id="cuenca_alrededores",
            name="Cuenca alrededores capital (Sotos, Arcas, Las Pernalosas)",
            distance_madrid_min=120,
            distance_beach_min=None,
            distance_natural_pools_min=18,
            distance_supermarket_min=12,
            distance_health_center_min=12,
            distance_hospital_min=12,
            fire_risk=FireRisk.MEDIO,
            zone_preference=4.0,
            price_min=185_000,
            price_max=285_000,
            fotocasa_search_urls=(),
            habitaclia_search_urls=(
                "https://www.habitaclia.com/casas-cuenca.htm",
            ),
            pisos_search_urls=(
                "https://www.pisos.com/venta/casas-cuenca/habitaciones-3/jardin/",
            ),
            idealista_alert_keywords=("sotos", "arcas", "pernalosas", "cuenca"),
        ),
        Zone(
            id="burgos_norte_merindad",
            name="Burgos norte / Merindad de Mena (Medina de Pomar, Villarcayo)",
            distance_madrid_min=165,
            distance_beach_min=45,
            distance_natural_pools_min=20,
            distance_supermarket_min=8,
            distance_health_center_min=5,
            distance_hospital_min=55,
            fire_risk=FireRisk.MUY_BAJO,
            zone_preference=6.0,
            price_min=100_000,
            price_max=230_000,
            fotocasa_search_urls=(),
            habitaclia_search_urls=(
                "https://www.habitaclia.com/casas-burgos.htm",
            ),
            pisos_search_urls=(
                "https://www.pisos.com/venta/casas-burgos/habitaciones-3/jardin/",
            ),
            idealista_alert_keywords=("medina de pomar", "villarcayo", "merindad de mena"),
        ),
        Zone(
            id="cantabria_liebana",
            name="Cantabria Liebana / Potes",
            distance_madrid_min=210,
            distance_beach_min=35,
            distance_natural_pools_min=10,
            distance_supermarket_min=5,
            distance_health_center_min=5,
            distance_hospital_min=50,
            fire_risk=FireRisk.BAJO,
            zone_preference=9.0,
            price_min=270_000,
            price_max=350_000,
            fotocasa_search_urls=(),
            habitaclia_search_urls=(
                "https://www.habitaclia.com/casas-potes.htm",
            ),
            pisos_search_urls=(
                "https://www.pisos.com/venta/casas-potes/habitaciones-3/jardin/",
            ),
            idealista_alert_keywords=("potes", "liebana", "camaleno"),
        ),
        Zone(
            id="asturias_oriente",
            name="Asturias oriental (Villaviciosa, Ribadesella, Colunga)",
            distance_madrid_min=255,
            distance_beach_min=5,
            distance_natural_pools_min=15,
            distance_supermarket_min=8,
            distance_health_center_min=10,
            distance_hospital_min=40,
            fire_risk=FireRisk.MEDIO,
            zone_preference=9.0,
            price_min=200_000,
            price_max=450_000,
            fotocasa_search_urls=(),
            habitaclia_search_urls=(
                "https://www.habitaclia.com/casas-villaviciosa.htm",
                "https://www.habitaclia.com/casas-ribadesella.htm",
            ),
            pisos_search_urls=(
                "https://www.pisos.com/venta/casas-villaviciosa/habitaciones-3/jardin/",
                "https://www.pisos.com/venta/casas-ribadesella/habitaciones-3/jardin/",
            ),
            idealista_alert_keywords=("villaviciosa", "ribadesella", "colunga", "lastres"),
        ),
    ]
}
